runtime: java7
inbound_services:
- warmup
derived_file_type:
- java_precompiled
threadsafe: True
auto_id_policy: default
api_version: '1.0'
handlers:
- url: (/_ah/push-handlers)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: optional
- url: (/_ah/push-handlers/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: optional
- url: (/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: /_ah/push-handlers/.*/
  script: unused
  login: admin
  secure: optional
- url: /
  script: unused
  login: optional
  secure: optional
- url: /_ah/push-handlers
  script: unused
  login: admin
  secure: optional
- url: /_ah/push-handlers/
  script: unused
  login: admin
  secure: optional
- url: /_ah/push-handlers/.*\.jsp
  script: unused
  login: admin
  secure: optional
- url: /.*/
  script: unused
  login: optional
  secure: optional
- url: /_ah/push-handlers/.*
  script: unused
  login: admin
  secure: optional
- url: .*\.jsp
  script: unused
  login: optional
  secure: optional
- url: /_ah/.*
  script: unused
  login: optional
  secure: optional
- url: /fetch_messages
  script: unused
  login: optional
  secure: optional
- url: /send_message
  script: unused
  login: optional
  secure: optional
- url: /init_servlet
  script: unused
  login: optional
  secure: optional
